server:
  port: 8081

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=medicare-sql-server;encrypt=false
    username: sa
    password: SenhaExemplo2024!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: user

api:
  security:
    token:
      secret: ${JWT_SECRET:my-very-strong-secret-key-of-32-characters}

swagger:
  api:
    docs:
      url: http://localhost:8081/v3/api-docs
  ui:
    url: http://localhost:8081/swagger-ui.html